runtime: python310

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

handlers:
  - url: /static
    static_dir: static/
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /.*
    script: auto
